<a href="https://colab.research.google.com/github/Park20182618/dl17/blob/main/notebook/ch02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# chap02 - numpy
import numpy as np


In [4]:

# ndarray
a = np.array([1, 2, 3])

print(type(a))

a[0]


<class 'numpy.ndarray'>


1

In [6]:

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b

b[0][2]


3

In [8]:

a = np.array([[ 0, 1, 2],
 		[ 3, 4, 5],
		[ 6, 7, 8]])

print(a.shape,a.ndim,a.dtype,a.itemsize,a.size)


(3, 3) 2 int64 8 9


In [9]:


np.zeros( (3, 4) )	


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:

np.ones( (3, 4), dtype=np.int32 )


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [11]:

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:

x = np.ones(5, dtype=np.int64)

x


array([1, 1, 1, 1, 1])

In [13]:

print(np.arange(5))

print(np.arange(1, 6))

np.arange(1, 10, 2)


[0 1 2 3 4]
[1 2 3 4 5]


array([1, 3, 5, 7, 9])

In [18]:
# 주어진 범위를 n 개의 점으로 나눈다.
np.linspace(0, 10, 9)


array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [19]:

# array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:

# 배열 합치기
x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6], [7, 8]])

#
print(np.concatenate((x, y), axis=1))

print(np.vstack((x, y)))

print(np.hstack((x, y)))


[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [24]:

# reshape
a = np.arange(12)

print(a.shape)


array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [26]:

print(a.reshape(3, 4))

print(a.reshape(6, -1))
# -1은 끝까지

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [27]:

array = np.arange(30).reshape(-1, 10)

array , array.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]), (3, 10))

In [28]:

arr1, arr2 = np.split(array, [3], axis=1)

arr1

arr2


array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [29]:

# 차원 확장
a = np.array([1, 2, 3, 4, 5, 6])

a.shape


(6,)

In [30]:

a1 = a[np.newaxis, :]

a1, a1.shape


(array([[1, 2, 3, 4, 5, 6]]), (1, 6))

In [31]:

a2 = a[:, np.newaxis]

a2.shape


(6, 1)

In [32]:

# indexing & slicing
ages = np.array([18, 19, 25, 30, 28])

ages[1:3] , ages[:2] 


(array([19, 25]), array([18, 19]))

In [33]:

y = ages > 20

y

ages[ ages > 20 ]


array([25, 30, 28])

In [ ]:

# 인덱싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0, 2]

a[0, 0] = 12

a


In [35]:

# 슬라이싱
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3]


array([[2, 3],
       [5, 6]])

### numpy 연산
- elementwise operation
- vectorwise operation

In [37]:

# operation of arrays
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[1, 1], [1, 1], [1, 1]])

result = arr1 + arr2

result


array([[2, 3],
       [4, 5],
       [6, 7]])

### 브로드캐스팅Broadcasting

In [38]:

miles = np.array([1, 2, 3])

result = miles * 1.6

result


array([1.6, 3.2, 4.8])

In [39]:
# Elementwise operation
arr1 = np.array([[1, 2], [3, 4], [5, 6]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 * arr2

result


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [40]:
# Vectorwise operation
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2 = np.array([[2, 2], [2, 2], [2, 2]])

result = arr1 @ arr2

result


array([[12, 12],
       [30, 30],
       [48, 48]])

In [41]:
arr1.dot(arr2) # == @연산자와 동일

array([[12, 12],
       [30, 30],
       [48, 48]])

In [44]:

A = np.array([0, 1, 2, 3])

10 * np.sin(A)

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a.sum(),a.min(axis=0),a.max()


(45, array([1, 2, 3]), 9)

In [43]:
scores = np.array([[99, 93, 60], [98, 82, 93],
               [93, 65, 81], [78, 82, 81]])    

scores.mean(axis=0)


array([92.  , 80.5 , 78.75])

## 무작위 수 배열

In [56]:
# random numbers
np.random.seed(100)

# np.random.rand(5), np.random.rand(5)

# np.random.rand(5, 3)

# np.random.randn(5)

np.random.randn(5, 4)


array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

### [DIY]
- 컬러 이미지 100장을 무작위로 생성
- 이미지 크기는 28 X 28 로 한다.

In [59]:
image100 = np.random.randn(100, 28, 28, 3)
image100.shape

(100, 28, 28, 3)

In [60]:
m, sigma = 10, 2

m + sigma*np.random.randn(5)


array([ 7.21244686, 11.41734976,  9.05216287, 10.814912  , 13.79504345])

In [63]:

mu, sigma = 0, 0.1 	# 평균과 표준 편차

np.random.normal(mu, sigma, 5)


array([ 0.02483539, -0.02557945,  0.11837775,  0.09662722, -0.15442787])

### np.unique() 중복제거

In [64]:
# unique() 중복제거
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
# a.size
unique_values = np.unique(a)
unique_values


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
# return_index, 해당 원소가 가장 처음나온 index return
np.unique(a, return_index=True)

uv,ui = np.unique(a, return_index=True)
uv, ui

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [70]:
# return_counts, 해당 원소가 몇 개 중복되었는지 return
uv, uc = np.unique(a, return_counts=True)
uv,uc

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [71]:
# 전치행렬 생성
# Transpose of an array
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.T)

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])



[[1 3 5]
 [2 4 6]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# flatten() 행렬 1차원화
x.flatten()


In [ ]:

########################
# Pandas
import numpy as np
import pandas as pd

x = pd.read_csv('countries.csv', header=0).values
print(x)

########################
# matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y1 = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
Y2 = [20.1, 23.1, 23.8, 25.9, 23.4, 25.1, 26.3]

plt.plot(X, Y1, label="Seoul")		# 분리시켜서 그려도 됨
plt.plot(X, Y2, label="Busan")		# 분리시켜서 그려도 됨
plt.xlabel("day")
plt.ylabel("temperature")
plt.legend(loc="upper left")
plt.title("Temperatures of Cities")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
plt.plot(X, [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4], "sm")
plt.show()


import matplotlib.pyplot as plt
# %matplotlib inline

X = [ "Mon", "Tue", "Wed", "Thur", "Fri",  "Sat", "Sun" ] 
Y = [15.6, 14.2, 16.3, 18.2, 17.1, 20.2, 22.4]
plt.bar(X, Y)
plt.show()



import matplotlib.pyplot as plt
import numpy as np

numbers = np.random.normal(size=10000)

plt.hist(numbers)
plt.xlabel("value")
plt.ylabel("freq")
plt.show()


import matplotlib.pyplot as plt
import numpy as np
X = np.arange(0, 10)
Y = X**2
plt.plot(X, Y)
plt.show()


X = np.arange(0, 10)
Y1 = np.ones(10)
Y2 = X 
Y3 = X**2 
plt.plot(X, Y1, X, Y2, X, Y3)
plt.show()


import matplotlib.pyplot as plt 
import numpy as np 
  
X = np.linspace(-10, 10, 101) 
Y = 1/(1 + np.exp(-X)) 
  
plt.plot(X, Y) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X)") 
plt.show() 


import matplotlib.pyplot as plt
import numpy as np

def sigmoid(x):
    s=1/(1+np.exp(-x))
    ds=s*(1-s)  		# 시그모이드 함수 1차 미분 함수
    return s,ds

X = np.linspace(-10, 10, 101) 
Y1, Y2 = sigmoid(X)
  
plt.plot(X, Y1, X, Y2) 
plt.xlabel("x") 
plt.ylabel("Sigmoid(X), Sigmoid'(X)") 
plt.show() 





